{
	"_Type": "Action.Type.OfflineOData.Upload",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/MesurePointGRT/Actions/Service/SyncFailureMessage.action",
	"OnSuccess": "/MesurePointGRT/Actions/Service/DownloadStartedMessage.action",
	"Service": "/MesurePointGRT/Services/MesurePoints.service"
}